[package]
name = "my_rust_project_one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
csv = "1.3.0"
thiserror = "1.0.56"
uom = "0.35.0"
